### ISSUE TITLE
Incorrect import generated for `Map`

### ISSUE THREAD

**Issue by fosskers** [eskimor/purescript-bridge#38] opened 2018-01-30 22:06 UTC
Hi there, I notice that when a type I want to bridge over to purescript contains a `Map`, like:

```haskell
data Blog = Blog { title :: Text, freqs :: M.Map Text Int } deriving (Generic, ToJSON)
```
the resulting Purescript will contain:
```
import Data.Map.Internal (Map)
```
which doesn't compile. Manually removing the `.Internal` fixes the break, but doing so ruins the whole point of auto-generating code :(

Thoughts?

**Comment by eskimor** [comment] 2018-02-01 14:11
The problem is there is no predefined bridge for Map, you have to provide one yourself with a psType that defines the proper import. Unfortunately we can't easily add such a bridge to purescript-bridge, because for Generic support a newtype wrapper is needed, see your other issue #39 . Adding a custom bridge should be easy though, see how the [`defaultBridge`](https://github.com/eskimor/purescript-bridge/blob/master/src/Language/PureScript/Bridge.hs#L98) is defined to get an idea. Also have a look at the existing primitive [bridges](https://github.com/eskimor/purescript-bridge/blob/master/src/Language/PureScript/Bridge/Primitives.hs) and existing [psTypes](https://github.com/eskimor/purescript-bridge/blob/master/src/Language/PureScript/Bridge/PSTypes.hs).

**Comment by fosskers** [comment] 2018-02-01 15:21
Thanks!

**Comment by eskimor** [comment] 2018-02-01 15:45
You are welcome! Closing, please re-open if this is a mistake.

**Closed by eskimor** 2018-02-01 15:45 UTC
